#!/bin/bash
# Dev server wrapper that finds available ports for multi-worktree development
#
# Strategy:
# 1. Scan actual port usage (not files) to find what's in use
# 2. Pick first available port pair (API: 3000+, Web: 5173+)
# 3. Write .ports file for reference (which worktree is where)
# 4. Start dev servers with those ports

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(dirname "$SCRIPT_DIR")"

# Base ports
API_BASE=3000
WEB_BASE=5173

# Find an available port starting from base
find_available_port() {
  local base=$1
  local port=$base
  local max_attempts=20

  for ((i=0; i<max_attempts; i++)); do
    if ! lsof -i:$port >/dev/null 2>&1; then
      echo $port
      return 0
    fi
    ((port++))
  done

  echo "ERROR: Could not find available port after $max_attempts attempts (starting from $base)" >&2
  return 1
}

# Find available ports
echo "Finding available ports..."
API_PORT=$(find_available_port $API_BASE)
WEB_PORT=$(find_available_port $WEB_BASE)

echo "Using API port: $API_PORT"
echo "Using Web port: $WEB_PORT"

# Write .ports file for reference
cat > "$ROOT_DIR/.ports" << EOF
# Auto-generated by scripts/dev.sh
# This file shows which ports this worktree's dev server is using
# DO NOT EDIT - will be overwritten on next dev start
API=$API_PORT
WEB=$WEB_PORT
STARTED=$(date -Iseconds)
WORKTREE=$(basename "$ROOT_DIR")
EOF

echo "Wrote .ports file"

# Clean up .ports file on exit
cleanup() {
  if [ -f "$ROOT_DIR/.ports" ]; then
    rm -f "$ROOT_DIR/.ports"
    echo "Cleaned up .ports file"
  fi
}
trap cleanup EXIT INT TERM

# Export environment variables and start dev servers
export PORT=$API_PORT
export CORS_ORIGIN="http://localhost:$WEB_PORT"
export VITE_PORT=$WEB_PORT
export VITE_API_URL="http://localhost:$API_PORT"

echo "Starting dev servers..."
echo "  API: http://localhost:$API_PORT"
echo "  Web: http://localhost:$WEB_PORT"
echo ""

cd "$ROOT_DIR"
pnpm --parallel --recursive run dev
