# Auto-generated from SSM Parameter Store
# Source: /ship/terraform-config/dev/*
# Generated: 2026-01-23T15:21:01Z
#
# DO NOT EDIT THIS FILE DIRECTLY
# Update the SSM parameters and re-run: ./scripts/sync-terraform-config.sh dev

environment = "dev"
app_domain_name = "dev.ship.awsdev.treasury.gov"
route53_zone_id = "Z0264966N8H7T352LP6P"
eb_environment_cname = "ship-api-dev.eba-quvxaryh.us-east-1.elasticbeanstalk.com"
